# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import szeol.main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20170217_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description', max_length=255)),
                ('order_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Sent to storyhouse'), (3, 'Shipping'), (4, 'Delivered')], default=0, help_text='Order status')),
                ('payment_status', models.IntegerField(choices=[(0, 'Not started'), (1, 'Waiting for payment'), (2, 'Payment collected by seller'), (3, 'Payment collected by storyhouse')], default=0, help_text='Order status')),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('when_created', models.DateTimeField(db_index=True, default=szeol.main.utils.default_now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
