# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not started'), (1, 'Waiting for payment'), (2, 'Payment collected by seller'), (3, 'Payment in advance by seller'), (4, 'Payment collected by storyhouse')], default=0, help_text='Order status'),
        ),
    ]
