# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Discount', max_digits=10),
        ),
    ]
