# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Name', max_length=50),
        ),
    ]
