# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170319_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(help_text='Address', max_length=255, null=True),
        ),
    ]
